In [22]:
!pip install pyswarm
!pip install psopy

distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


# Ejercicio 

Minimice la siguiente función 

$f(x) = x^2$

In [21]:
from pyswarm import pso
import numpy as np

In [23]:
def f(x):
    x1 = x[0]
    return x1**2

In [36]:
lb = [-1000000]
ub = [1000000]
pso(f, lb, ub)

Stopping search: Swarm best objective change less than 1e-08


(array([-8.44671902e-07]), 7.134706214759553e-13)

# Ejercicio


Minimice la siguiente función 

$$f(x) = x^2$$

sujeta a la restricción

$$ g(x) = x \geq 5$$

In [32]:
def f(x):
    x2 = x[0]
    return x2**2

In [33]:
def g(x):
    x2 = x[0]
    return [x-5]

In [34]:
lb = [-100000]
ub = [100000]
pso (f, lb, ub, f_ieqcons = g )

Stopping search: Swarm best position change less than 1e-08


(array([5.]), 25.00000004498648)

In [31]:
pso?

# Ejercicio

Una caja rectangular sin tapa se hace con $12 m^2$ de cartón.

Calcule el volumen máximo de esta caja.

Solucion:

Sean $x, y$ y $z$ el largo, el ancho
y la altura, respectivamente, de la caja medidos en metros. Buscamos maximizar

$$V=xyz $$

sujeta a la restricción

$$g(x,y,z) = 2xz + 2yz + xy = 12$$

In [42]:
def V(w):
    x = w[0]
    y = w[1]
    z = w[2]
    return -x*y*z

In [43]:
def g(w):
    x = w[0]
    y = w[1]
    z = w[2]
    return -2*x*z - 2*y*z - x*y + 12

In [47]:
lb = (0,0,0)
ub = (12, 12, 12)
pso (V, lb, ub, f_ieqcons = g,maxiter= 200 )

Stopping search: Swarm best position change less than 1e-08


(array([1.23555111, 3.5559237 , 0.79375086]), -3.487364595297982)

In [48]:
pso?

# Ejercicio

Un agricultor tiene $2 400$ metros de material y quiere construir una barda para
cercar un campo rectangular que bordea un río recto, de modo que no necesita barda a
lo largo del río. 

¿Cuáles son las dimensiones que debe tener el campo para encerrar el
área más grande?

### Solución

- Queremos maximizar el área $A$ del rectángulo.

$$A(x,y) = xy $$

Ademas tenemos una restriccion, utilizamos la información dada de que la longitud total de la barda es $2400$ metros

$$2x + y = 2400 $$

In [83]:
def A(w):
    x = w[0]
    y = w[1]
    return -x*y
def g(w):
    x = w[0]
    y = w[1]
    return  [(2*x + y - 2400)*-1]

In [85]:
lb = (0,0)
ub = (2000, 2000)
pso (A, lb, ub, f_ieqcons = g,maxiter= 300 )

Stopping search: Swarm best position change less than 1e-08


(array([ 594.36510103, 1211.26974634]), -719936.4651593361)

# Ejercicio

Se va un fabricar una lata que ha de contener $1 L$ de aceite. Encuentre
las dimensiones que debe tener la lata de manera que minimicen el costo del metal para fabricarla.

De esta manera, el área superficial es
$$A(r,h) = 2\pi r^2 + 2\pi r h  $$

El volumen está dado como $1 L$, que tomamos como $1000$ $cm^3$

$$\pi r^2h=1000 $$



In [90]:
from sympy import*
def A(w):
    r = w[0]
    h = w[1]
    return 2*pi*r**2 + 2*pi*r*h
def g(w):
    r = w[0]
    h = w[1]
    return pi*r**2*h - 1000

In [91]:
lb = (0, 0)
ub = (1000, 1000)
pso (A, lb, ub, f_ieqcons = g,maxiter= 300 )

Stopping search: Swarm best position change less than 1e-08


(array([ 5.26681816, 11.47502073]), 176.352442255088*pi)